/**
 * reportWorkbook.js — the report as an Excel workbook, one sheet per section.
 *
 * A CSV cannot hold more than one table, and a report is eight of them, so the
 * spreadsheet export is a real .xlsx built from the same dataset as the PDF.
 *
 * "INTERACTIVE" MEANS IT STAYS LIVE IN EXCEL:
 *
 *   * every table is an Excel Table, with filter and sort buttons on its header;
 *   * header rows are frozen, so they stay put while scrolling a month of days;
 *   * totals are SUBTOTAL formulas, not pasted numbers — filter the day table to
 *     weekends and the totals recalculate for the weekends;
 *   * money is a number in rupee format, never text, so it can be summed and
 *     charted; percentages are real percentages;
 *   * occupancy carries data bars, and the Summary sheet links to every other
 *     sheet.
 *
 * The Summary sheet repeats the Report ID, period, generation time and the
 * fingerprint, so a workbook passed around on its own still says what it is.
 */

const ExcelJS = require('exceljs');

const BRAND = 'FF075E54';
const BRAND_LIGHT = 'FFE7F3F1';
const INK = 'FF111B21';
const MUTED = 'FF667781';
const RUPEE = '"₹"#,##0';
const COUNT = '#,##0';
const PERCENT = '0.0%';

const colLetter = (n) => {
  let s = '';
  for (let x = n; x > 0; x = Math.floor((x - 1) / 26)) s = String.fromCharCode(65 + ((x - 1) % 26)) + s;
  return s;
};

/** A titled sheet: heading, a line of context, then a live Excel Table. */
function tableSheet(wb, { name, title, note, columns, rows, totals = {}, dataBarColumn = null }) {
  const ws = wb.addWorksheet(name, {
    properties: { tabColor: { argb: BRAND } },
    views: [{ state: 'frozen', ySplit: 4 }],
  });

  ws.getCell('A1').value = title;
  ws.getCell('A1').font = { bold: true, size: 14, color: { argb: BRAND } };
  ws.getCell('A2').value = note || '';
  ws.getCell('A2').font = { size: 9, color: { argb: MUTED }, italic: true };

  const hasTotals = Object.keys(totals).length > 0;

  ws.addTable({
    name: name.replace(/[^A-Za-z0-9]/g, '') || 'Table',
    ref: 'A4',
    headerRow: true,
    totalsRow: hasTotals,
    style: { theme: 'TableStyleMedium7', showRowStripes: true },
    columns: columns.map((c, i) => ({
      name: c.header,
      filterButton: true,
      ...(hasTotals ? (i === 0 ? { totalsRowLabel: 'Total' } : totals[c.key] ? { totalsRowFunction: totals[c.key] } : {}) : {}),
    })),
    rows: rows.map((r) => columns.map((c) => (typeof c.value === 'function' ? c.value(r) : r[c.key]))),
  });

  columns.forEach((c, i) => {
    const col = ws.getColumn(i + 1);
    col.width = c.width || Math.max(12, String(c.header).length + 4);
    if (c.format) col.numFmt = c.format;
    col.alignment = { vertical: 'middle', horizontal: c.align || (c.format ? 'right' : 'left') };
  });

  if (dataBarColumn) {
    const idx = columns.findIndex((c) => c.key === dataBarColumn) + 1;
    if (idx > 0 && rows.length) {
      const L = colLetter(idx);
      ws.addConditionalFormatting({
        ref: `${L}5:${L}${4 + rows.length}`,
        rules: [{ type: 'dataBar', minLength: 0, maxLength: 100, color: { argb: 'FF00A884' },
          cfvo: [{ type: 'num', value: 0 }, { type: 'num', value: 1 }] }],
      });
    }
  }

  return ws;
}

async function workbook(report, { reportNo, generatedAt, generatedBy }) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Pravesha';
  wb.company = 'ServerPe App Solutions';
  wb.title = `Pravesha report ${reportNo}`;
  wb.created = new Date(generatedAt);
  wb.calcProperties.fullCalcOnLoad = true;

  const p = report.period;
  const s = report.summary;
  const f = report.finance;
  const when = new Date(generatedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
  const periodText = p.from === p.to ? p.from : `${p.from} to ${p.to}`;
  const kindText = { daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly', custom: 'Custom period' }[p.kind];

  /* ── Summary ─────────────────────────────────────────────────────────── */
  const sum = wb.addWorksheet('Summary', { properties: { tabColor: { argb: BRAND } } });
  sum.columns = [{ width: 38 }, { width: 22 }, { width: 4 }, { width: 38 }, { width: 22 }];

  sum.mergeCells('A1:E1');
  sum.getCell('A1').value = `Pravesha — ${kindText} report`;
  sum.getCell('A1').font = { bold: true, size: 18, color: { argb: 'FFFFFFFF' } };
  sum.getCell('A1').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND } };
  sum.getRow(1).height = 30;

  const meta = [
    ['Report ID', reportNo], ['Period', `${periodText} (${p.days} day${p.days === 1 ? '' : 's'})${p.partial ? ' — to date' : ''}`],
    ['Generated', `${when} IST`], ['Generated by', generatedBy || '—'],
    ['Basis', 'Operations by travel date · money by payment date'],
  ];
  meta.forEach(([k, v], i) => {
    sum.getCell(`A${3 + i}`).value = k;
    sum.getCell(`A${3 + i}`).font = { color: { argb: MUTED } };
    sum.mergeCells(`B${3 + i}:E${3 + i}`);
    sum.getCell(`B${3 + i}`).value = v;
    sum.getCell(`B${3 + i}`).font = { bold: true, color: { argb: INK } };
  });

  const block = (startRow, col, heading, lines) => {
    const L = col === 1 ? ['A', 'B'] : ['D', 'E'];
    const h = sum.getCell(`${L[0]}${startRow}`);
    h.value = heading;
    h.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    h.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND } };
    sum.getCell(`${L[1]}${startRow}`).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND } };
    lines.forEach(([label, value, fmt], i) => {
      const r = startRow + 1 + i;
      sum.getCell(`${L[0]}${r}`).value = label;
      const cell = sum.getCell(`${L[1]}${r}`);
      cell.value = value === null || value === undefined ? 'not reported' : value;
      if (fmt && typeof value === 'number') cell.numFmt = fmt;
      cell.alignment = { horizontal: 'right' };
      if (i % 2 === 0) {
        sum.getCell(`${L[0]}${r}`).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND_LIGHT } };
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND_LIGHT } };
      }
    });
    return startRow + lines.length + 2;
  };

  let left = 9;
  let right = 9;
  left = block(left, 1, 'Visitors and entries', [
    ['Bookings', s.bookings, COUNT], ['Entries', s.entries, COUNT], ['Visitors', s.visitors, COUNT],
    ['Yet to arrive', s.yetToArrive, COUNT], ['Skipped (no-show)', s.skipped, COUNT],
    ['Abandoned at payment', s.abandoned, COUNT], ['Average entries per day', s.averagePerDay, '#,##0.0'],
    ['Show-up rate', s.showUpRate / 100, PERCENT], ['Occupancy', s.occupancy / 100, PERCENT],
  ]);
  right = block(right, 2, 'Gate and verification', [
    ['Look-ups at the gate', s.lookups, COUNT], ['Valid', s.valid, COUNT], ['Duplicate presentations', s.duplicate, COUNT],
    ['Invalid passes', s.invalid, COUNT], ['Admitted outside slot', s.admittedAnyway, COUNT],
    ['Invalid attempt rate', s.invalidRate / 100, PERCENT], ['Duplicate rate', s.duplicateRate / 100, PERCENT],
  ]);
  left = block(left, 1, 'Financial split (payment date)', [
    ['Total collected', f.collected, RUPEE], ['Tourism Department', f.department, RUPEE],
    [`Pravesha service fee (${f.serviceFeePercent}%)`, f.serviceFee, RUPEE], [`GST in service fee (${f.gstPercent}%)`, f.gst, RUPEE],
    ['Payment gateway charges', f.gateway, RUPEE], ['Refunds', f.refunds, RUPEE], ['Net Pravesha revenue', f.netPravesha, RUPEE],
  ]);
  right = block(right, 2, 'Visitors', [
    ['New visitors', report.visitors.new, COUNT], ['Returning visitors', report.visitors.returning, COUNT],
    ['Returning share', report.visitors.returningShare / 100, PERCENT],
    ['Came more than once this period', report.visitors.repeatWithinPeriod, COUNT],
    ['Visitors, previous period', report.visitors.previousPeriod, COUNT],
    ['Visitor growth', report.visitors.growth === null ? null : report.visitors.growth / 100, PERCENT],
  ]);

  const peaksRow = Math.max(left, right);
  block(peaksRow, 1, 'Peaks', [
    ['Highest traffic day', report.peaks.highestDay ? `${report.peaks.highestDay.day} · ${report.peaks.highestDay.entries}` : null],
    ['Lowest traffic day', report.peaks.lowestDay ? `${report.peaks.lowestDay.day} · ${report.peaks.lowestDay.entries}` : null],
    ['Peak hour', report.peaks.peakHour ? `${report.peaks.peakHour.label} · ${report.peaks.peakHour.entries}` : null],
    ['Busiest slot', report.peaks.busiestSlot ? report.peaks.busiestSlot.label : null],
  ]);

  /* A contents list that jumps to each sheet. */
  const sheets = ['Daily', 'Weekly', 'Hourly', 'Vehicles', 'Slots', 'Staff', 'Finance'];
  block(peaksRow, 2, 'Sheets in this workbook', sheets.map((name) => [name, '→ open']));
  sheets.forEach((name, i) => {
    const cell = sum.getCell(`E${peaksRow + 1 + i}`);
    cell.value = { text: `→ ${name}`, hyperlink: `#'${name}'!A1` };
    cell.font = { color: { argb: 'FF008069' }, underline: true };
  });

  const fpRow = peaksRow + sheets.length + 3;
  sum.getCell(`A${fpRow}`).value = 'Fingerprint (SHA-256 of the figures)';
  sum.getCell(`A${fpRow}`).font = { size: 8, color: { argb: MUTED } };
  sum.mergeCells(`B${fpRow}:E${fpRow}`);
  sum.getCell(`B${fpRow}`).value = report.fingerprint;
  sum.getCell(`B${fpRow}`).font = { size: 8, color: { argb: MUTED }, name: 'Consolas' };

  /* ── Daily ───────────────────────────────────────────────────────────── */
  tableSheet(wb, {
    name: 'Daily',
    title: 'Day by day',
    note: 'Bookings, entries and vehicles by travel date; money by payment date. Filter the table — the totals follow.',
    columns: [
      { header: 'Date', key: 'day', width: 12 },
      { header: 'Bookings', key: 'bookings', format: COUNT },
      { header: 'Entries', key: 'entries', format: COUNT },
      { header: 'Visitors', key: 'visitors', format: COUNT },
      { header: 'Bikes', key: 'bikes', format: COUNT },
      { header: 'Cars', key: 'cars', format: COUNT },
      { header: 'Toofan', key: 'toofans', format: COUNT },
      { header: 'TT', key: 'tts', format: COUNT },
      { header: 'Skipped', key: 'skipped', format: COUNT },
      { header: 'Invalid', key: 'invalid', format: COUNT },
      { header: 'Duplicate', key: 'duplicate', format: COUNT },
      { header: 'Collected', key: 'collected', format: RUPEE, width: 14 },
      { header: 'Department', key: 'department', format: RUPEE, width: 14 },
      { header: 'Service fee', key: 'serviceFee', format: RUPEE, width: 14 },
      { header: 'GST', key: 'gst', format: RUPEE },
      { header: 'Gateway', key: 'gateway', format: RUPEE },
    ],
    rows: report.daily,
    totals: Object.fromEntries(['bookings', 'entries', 'visitors', 'bikes', 'cars', 'toofans', 'tts', 'skipped',
      'invalid', 'duplicate', 'collected', 'department', 'serviceFee', 'gst', 'gateway'].map((k) => [k, 'sum'])),
  });

  /* ── Weekly ──────────────────────────────────────────────────────────── */
  tableSheet(wb, {
    name: 'Weekly',
    title: 'Week by week',
    note: 'Weeks start on Monday. A week at the edge of the period covers only the days inside it.',
    columns: [
      { header: 'Week of', key: 'week', width: 12 },
      { header: 'Days', key: 'days', format: COUNT },
      { header: 'Bookings', key: 'bookings', format: COUNT },
      { header: 'Entries', key: 'entries', format: COUNT },
      { header: 'Collected', key: 'collected', format: RUPEE, width: 14 },
      { header: 'Department', key: 'department', format: RUPEE, width: 14 },
      { header: 'Service fee', key: 'serviceFee', format: RUPEE, width: 14 },
    ],
    rows: report.weekly,
    totals: { days: 'sum', bookings: 'sum', entries: 'sum', collected: 'sum', department: 'sum', serviceFee: 'sum' },
  });

  /* ── Hourly ──────────────────────────────────────────────────────────── */
  tableSheet(wb, {
    name: 'Hourly',
    title: 'Entries by hour of day',
    note: 'Across the whole period. Sort by Entries to see the busiest hours first.',
    columns: [
      { header: 'Hour', key: 'label', width: 10 },
      { header: 'Entries', key: 'entries', format: COUNT },
    ],
    rows: report.hours,
    totals: { entries: 'sum' },
  });

  /* ── Vehicles ────────────────────────────────────────────────────────── */
  tableSheet(wb, {
    name: 'Vehicles',
    title: 'Vehicles and revenue by type',
    note: 'By travel date. Pass value = department entry fee + Pravesha service fee.',
    columns: [
      { header: 'Vehicle type', key: 'label', width: 22 },
      { header: 'Passes', key: 'passes', format: COUNT },
      { header: 'Entries', key: 'entries', format: COUNT },
      { header: 'Share of entries', key: 'share', format: PERCENT, value: (r) => r.shareOfEntries / 100, width: 16 },
      { header: 'Pass value', key: 'passValue', format: RUPEE, width: 14 },
      { header: 'Department', key: 'department', format: RUPEE, width: 14 },
      { header: 'Service fee', key: 'serviceFee', format: RUPEE, width: 14 },
    ],
    rows: report.vehicles,
    totals: { passes: 'sum', entries: 'sum', passValue: 'sum', department: 'sum', serviceFee: 'sum' },
  });

  /* ── Slots ───────────────────────────────────────────────────────────── */
  tableSheet(wb, {
    name: 'Slots',
    title: 'Slot utilisation',
    note: 'Capacity is the places offered across every day of the period.',
    columns: [
      { header: 'Slot', key: 'label', width: 30 },
      { header: 'Place', key: 'place', width: 16 },
      { header: 'Capacity', key: 'capacity', format: COUNT },
      { header: 'Booked', key: 'booked', format: COUNT },
      { header: 'Entered', key: 'entered', format: COUNT },
      { header: 'Occupancy', key: 'occ', format: PERCENT, value: (r) => r.occupancy / 100 },
      { header: 'Show-up', key: 'show', format: PERCENT, value: (r) => r.showUp / 100 },
    ],
    rows: report.slots,
    totals: { capacity: 'sum', booked: 'sum', entered: 'sum' },
    dataBarColumn: 'occ',
  });

  /* ── Staff ───────────────────────────────────────────────────────────── */
  tableSheet(wb, {
    name: 'Staff',
    title: 'Checkpost staff',
    note: 'Check time is measured by the gate app, from opening a pass to recording the entry.',
    columns: [
      { header: 'Staff', key: 'name', width: 22 },
      { header: 'Checks', key: 'checks', format: COUNT },
      { header: 'Valid', key: 'valid', format: COUNT },
      { header: 'Invalid', key: 'invalid', format: COUNT },
      { header: 'Duplicate', key: 'duplicate', format: COUNT },
      { header: 'Admitted outside slot', key: 'admittedAnyway', format: COUNT, width: 22 },
      { header: 'Average check (sec)', key: 'avg', format: '0.0', value: (r) => (r.averageMs === null ? null : r.averageMs / 1000), width: 20 },
      { header: 'Fastest (sec)', key: 'fast', format: '0.0', value: (r) => (r.fastestMs === null ? null : r.fastestMs / 1000) },
      { header: 'Slowest (sec)', key: 'slow', format: '0.0', value: (r) => (r.slowestMs === null ? null : r.slowestMs / 1000) },
      { header: 'Peak hour', key: 'peak', value: (r) => (r.peakHour ? r.peakHour.label : ''), width: 12 },
    ],
    rows: report.staff,
    totals: { checks: 'sum', valid: 'sum', invalid: 'sum', duplicate: 'sum', admittedAnyway: 'sum' },
  });

  /* ── Staff, day by day ───────────────────────────────────────────────── */
  const sd = report.staffDaily;
  if (sd && sd.staff.length && sd.entries.length) {
    /* One column per person, every person — the PDF stops at six for paper,
       this is where the rest are. */
    const people = sd.staff.map((x) => x.name);
    const perDay = (metric) => sd[metric].map((row) => ({ ...row }));
    tableSheet(wb, {
      name: 'StaffDaily',
      title: 'Staff day by day — vehicles admitted',
      note: 'Each staff member’s entries on each day of the period.',
      columns: [
        { header: 'Date', key: 'day', width: 12 },
        ...people.map((name) => ({ header: name, key: name, format: COUNT, value: (r) => r[name] || 0, width: Math.max(12, name.length + 4) })),
      ],
      rows: perDay('entries'),
      totals: Object.fromEntries(people.map((name) => [name, 'sum'])),
    });
    tableSheet(wb, {
      name: 'StaffSpeed',
      title: 'Staff day by day — average check time (seconds)',
      note: 'From opening a pass to recording the verdict. Blank where the person did not work that day.',
      columns: [
        { header: 'Date', key: 'day', width: 12 },
        ...people.map((name) => ({ header: name, key: name, format: '0.0', value: (r) => (r[name] === undefined ? null : r[name]), width: Math.max(12, name.length + 4) })),
      ],
      rows: perDay('seconds'),
    });
  }

  /* ── When they arrive ────────────────────────────────────────────────── */
  const pat = report.patterns;
  if (pat && pat.total > 0) {
    const hours = [];
    for (let h = 0; h < 24; h += 1) if (pat.byHour[h].entries > 0) hours.push(h);
    const hws = tableSheet(wb, {
      name: 'Arrivals',
      title: 'When they arrive — average vehicles admitted per hour, by weekday',
      note: 'The number in brackets is how many of that weekday fall in the period. Darker is busier.',
      columns: [
        { header: 'Weekday', key: 'day', width: 16, value: (r) => `${r.day} (${r.days})` },
        ...hours.map((h) => ({ header: pat.byHour[h].label, key: `h${h}`, format: '0.0', width: 9, value: (r) => r.hours[h].average })),
        { header: 'Total admitted', key: 'entries', format: COUNT, width: 16 },
      ],
      rows: pat.rows,
    });
    /* The same heat as the printed page: a colour scale over every hour cell. */
    if (hours.length) {
      hws.addConditionalFormatting({
        ref: `B5:${colLetter(hours.length + 1)}${4 + pat.rows.length}`,
        rules: [{ type: 'colorScale', cfvo: [{ type: 'min' }, { type: 'max' }],
          color: [{ argb: 'FFF2F5F5' }, { argb: 'FF00A884' }] }],
      });
    }
  }

  /* ── Where they come from ────────────────────────────────────────────── */
  const org = report.origins;
  if (org && org.vehicles > 0) {
    tableSheet(wb, {
      name: 'States',
      title: 'Where they come from — by state and union territory',
      note: `From the first two letters of the number plate. Counted by vehicle: ${org.vehicles} distinct vehicles made ${org.entries} arrivals.`,
      columns: [
        { header: 'State / UT', key: 'name', width: 34 },
        { header: 'Code', key: 'code', width: 8 },
        { header: 'Kind', key: 'kind', width: 16, value: (r) => ({ state: 'State', ut: 'Union territory', series: 'Bharat series' }[r.kind] || 'Not recognised') },
        { header: 'Vehicles', key: 'vehicles', format: COUNT },
        { header: 'Arrivals', key: 'entries', format: COUNT },
        { header: 'Share of vehicles', key: 'share', format: PERCENT, value: (r) => r.share / 100, width: 18 },
      ],
      rows: org.states,
      totals: { vehicles: 'sum', entries: 'sum' },
      dataBarColumn: 'share',
    });
    tableSheet(wb, {
      name: 'Districts',
      title: 'Where they come from — by district and registering office',
      note: 'From each vehicle’s registration certificate. Where none has been fetched, the RTO code on the plate is given and the office is marked not known.',
      columns: [
        { header: 'Place', key: 'place', width: 32, value: (r) => r.place || `${r.rtoCode} (office not known)` },
        { header: 'RTO code', key: 'rtoCode', width: 10 },
        { header: 'State / UT', key: 'stateName', width: 22 },
        { header: 'Vehicles', key: 'vehicles', format: COUNT },
        { header: 'Arrivals', key: 'entries', format: COUNT },
        { header: 'Share of vehicles', key: 'share', format: PERCENT, value: (r) => r.share / 100, width: 18 },
      ],
      rows: org.places,
      totals: { vehicles: 'sum', entries: 'sum' },
      dataBarColumn: 'share',
    });
  }

  /* ── Finance ─────────────────────────────────────────────────────────── */
  const fin = wb.addWorksheet('Finance', { properties: { tabColor: { argb: BRAND } } });
  fin.columns = [{ width: 42 }, { width: 18 }, { width: 14 }];
  fin.getCell('A1').value = 'Collection distribution';
  fin.getCell('A1').font = { bold: true, size: 14, color: { argb: BRAND } };
  fin.getCell('A2').value = 'By payment date — the basis that reconciles with the bank. Net and shares are formulas.';
  fin.getCell('A2').font = { size: 9, italic: true, color: { argb: MUTED } };

  const lines = [
    ['Total collected', f.collected],
    ['Tourism Department (entry fees)', f.department],
    [`Pravesha service fee (${f.serviceFeePercent}%)`, f.serviceFee],
    [`GST within service fee (${f.gstPercent}%)`, f.gst],
    ['Payment gateway charges', f.gateway === null ? 0 : f.gateway],
    ['Refunds', f.refunds],
  ];
  fin.getRow(4).values = ['Line', 'Amount', 'Share'];
  fin.getRow(4).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  fin.getRow(4).eachCell((c) => { c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND } }; });
  lines.forEach(([label, value], i) => {
    const r = 5 + i;
    fin.getCell(`A${r}`).value = label;
    fin.getCell(`B${r}`).value = value;
    fin.getCell(`B${r}`).numFmt = RUPEE;
    fin.getCell(`C${r}`).value = { formula: `IF($B$5=0,0,B${r}/$B$5)` };
    fin.getCell(`C${r}`).numFmt = PERCENT;
  });
  fin.getCell('A11').value = 'Net Pravesha revenue';
  fin.getCell('A11').font = { bold: true };
  fin.getCell('B11').value = { formula: 'B7-B8-B9', result: f.netPravesha };
  fin.getCell('B11').numFmt = RUPEE;
  fin.getCell('B11').font = { bold: true, color: { argb: BRAND } };
  fin.getCell('A12').value = 'Collected after refunds';
  fin.getCell('B12').value = { formula: 'B5-B10', result: f.netCollected };
  fin.getCell('B12').numFmt = RUPEE;
  fin.getCell('A14').value = f.gateway === null
    ? 'Gateway charges are not yet reported by Razorpay for this period and are shown as zero.'
    : 'Gateway charges are as reported by Razorpay on each payment.';
  fin.getCell('A14').font = { size: 9, italic: true, color: { argb: MUTED } };

  return wb.xlsx.writeBuffer();
}

module.exports = { workbook };
